### ISSUE TITLE
add vue jsx transformer to esbuild

### ISSUE THREAD

**Issue by xxholly32** [egoist/rollup-plugin-esbuild#105]
i was use rollup-plugin-esbuild to my [vue3-components](https://github.com/xxholly32/vue3-general-components/blob/tsx/build/rollup.config.base.js)

but i found it`s to hard to work with vue-jsx. it always need transform

here is my transformer [vueJsxCompat.ts](https://github.com/xxholly32/vue3-general-components/blob/tsx/packages/vue-jsx-compat.ts) , copy form `vite`

After this step, all my `.tsx` files will add

```js
// add this line for vue-jsx
import { vueJsxCompat } from '../vue-jsx-compat';
```
other users repo [nova-next](https://github.com/em2046/nova-next/blob/master/src/components/button/NovaButton.tsx#L2) also have same problem, all the `.tsx` files will add this code

so i work with another plugin [rollup-plugin-vue-jsx-compat](https://github.com/xxholly32/rollup-plugin-vue-jsx)

here is the config

```js
const vueJsx = require("../dist/index");
const esbuild = require("rollup-plugin-esbuild");

export default {
  input: 'example/index.js',
  output: {
    file: 'example/dist/index.js',
    format: 'cjs',
  },
  plugins: [
    vueJsx(),
    esbuild({
      jsxFactory: "vueJsxCompat"
    }),
  ],
}
```

i was wandering is this [alpha-code](https://github.com/xxholly32/rollup-plugin-vue-jsx/blob/master/src/index.ts) design correct, and you may consider adding this feature to your project ?

**Comment by egoist** [comment]
```js
plugins: [
    vueJsx(),
    esbuild({
      jsxFactory: "vueJsxCompat"
    }),
],
```

this seems pretty straight-forward, just use your plugin with rollup-plugin-esbuild and it will just work.

**Comment by egoist** [comment]
I added a link here: https://github.com/egoist/rollup-plugin-esbuild/blob/master/README.md#use-with-vue-jsx
