### ISSUE TITLE
[feature] add loader to options

### ISSUE THREAD

**Issue by kzc** [egoist/rollup-plugin-esbuild#12]
Thanks for creating this plugin!

I've encountered a project where the files have a `.js` suffix but they're actually `jsx` format. It's fairly common for react projects. I couldn't find an existing option to set this. Patching the installed plugin to allow overriding the loader does the trick:

```patch
--- a/node_modules/rollup-plugin-esbuild/dist/index.js
+++ b/node_modules/rollup-plugin-esbuild/dist/index.js
@@ -54,4 +54,4 @@
       const result = await service.transform(code, {
-        loader,
-        target: options.target || "es2015",
+        loader: options.loader || loader,
+        target: options.target || "es2019",
         jsxFactory: options.jsxFactory,
```

I'd also recommend to up the default target to "es2019" since some TS features do not map correctly to ES2015 in esbuild.

**Edit:** patch updated

**Comment by kzc** [comment]
There's another loader setting I missed:
```patch
     async renderChunk(code) {
       if (options.minify && service) {
         const result = await service.transform(code, {
-          loader: "js",
+          loader: options.loader || "jsx",
           target: "esnext",
           minify: true
         });
```

**Comment by egoist** [comment]
PR welcome.

I think `loader` option should also be a function, so you can set loader based on file path.

**Comment by kzc** [comment]
I see your point.  Maybe an object literal mapping the file extensions to the correct loader could also be an option:
```
loader: {
  ".bar": "text",
  ".baz": "json"
}
```
But it would be nice if a default loader could be specified somehow. Is this too hacky?
```
loader: {
  "default": "tsx",
  ".dat": "base64"
}
```
