### ISSUE TITLE
rollup-plugin-dts cannot generate d.ts but only roll-up d.ts

### ISSUE THREAD

**Issue by fxxjdedd** [egoist/rollup-plugin-esbuild#169]
Hi, I'm trying use this plugin in my project, but I can't find a way to generate d.ts, it seems that rollup-plugin-esbuild delegates the task of generating d.ts to the user or other plugins (rollup-plugin-dts).

But I can not find a way to generate d.ts in rollup-plugin-dts either 🤣

**Comment by phoenisx** [comment]
Check this config for reference - https://github.com/pmndrs/react-spring/blob/v9/rollup.config.js

**Comment by courtyenn** [comment]
I am very confused how this library replaces `typescript2` but cannot generate `*.d.ts` files. There should be an option where we can...
