### ISSUE TITLE
Race condition fails the build with multiple chunks + minify

### ISSUE THREAD

**Issue by AlexGalays** [egoist/rollup-plugin-esbuild#177]
Preconditions: production build with `minify: true` and multiple `output` in the rollup config (I use one for modern browsers, and one for legacy browsers that instead will use the systemjs format)

The plugin prematurely closes the esbuild service while esbuild is still processing the second chunk/request, as seen in these logs:

![image](https://user-images.githubusercontent.com/1375586/103761865-a6552580-5017-11eb-800c-4f9876ba8ca0.png)

It seems like `generateBundle` (and thus, `stop()`) is called before the second Promise for `renderChunk` resolved. The esbuild service should probably be treated like a shared dependency (global state) for all chunks and only be stopped when all chunks are done?

**Comment by egoist** [comment]
shouldn't be a problem now.
