### ISSUE TITLE
Add option to pass through (parsed) tsconfig to avoid resolving the configuration in the transform step for every file

### ISSUE THREAD

**Issue by TomCaserta** [egoist/rollup-plugin-esbuild#212]
So I have a configuration that essentially adds every ts file in my project as an entry point. This plugin is of course perfectly capable of dealing with that however I notice that it's resolving the `tsconfig` and parsing it in the transform step. 

What would be nice is if there was an option to pass through an already parsed tsconfig file to the plugin to essentially make it clear I do not have a different configuration for every single file.

On top of that to make the whole parsing easier, this library could expose a utility function to load the tsconfig so you can pass it directly through to the options. 

For example proposed API:

```js
import esbuild, { loadTypescriptConfiguration } from 'rollup-plugin-esbuild';

/// ... rollup etc
esbuild({
    fullTsConfig: loadTypescriptConfiguration('./tsconfig.json),
});
```

Alternatively an option to just use the first tsconfig it finds when the plugin is loaded would be fine too.

**Comment by egoist** [comment]
the resolved tsconfig is actually cached already

**Comment by TomCaserta** [comment]
Ah, sorry I must have misunderstood what was happening when debugging another issue. I guess what I saw was it attempting to resolve recursively in every new directory it entered. Thank you, this can be closed then as I imagine the pathExists call for each new directory it enters is negligible.
