### ISSUE TITLE
Insufficient parameters supported by `esbuild.transform`

### ISSUE THREAD

**Issue by asins** [egoist/rollup-plugin-esbuild#245]
For example, now I want to use the `legalComments` parameter to modify the support for comments, but `rollup-plugin-esbuild` does not support it. I hope to support all the parameters of `esbuild` by default.

**Comment by jacksteamdev** [comment]
Looking at the code, `legalComments` does seem to be passed to esbuild:

https://github.com/egoist/rollup-plugin-esbuild/blob/875aed8d6e08d5573c0fa4d0d9402850cf3ac140/src/index.ts#L173-L184

Comments with `@preserve` are being removed for me too, but IDK if it's a problem with this library.

**Comment by sxzz** [comment]
Supported in the latest version.
