### ISSUE TITLE
Missing support for `jsx` option

### ISSUE THREAD

**Issue by maxmilton** [egoist/rollup-plugin-esbuild#261]
Recently esbuild v0.12.1 introduced the `jsx=preserve` option: <https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#0121>.

Would be great if `rollup-plugin-esbuild` would add support for passing the option through.

**Comment by egoist** [comment]
What's your use case? do you want to use other rollup plugins to handle JSX?

**Comment by BuptStEve** [comment]
> What's your use case? do you want to use other rollup plugins to handle JSX?

yeah, such as transforming Vue's jsx by `@vue/babel-preset-jsx`

**Comment by maxmilton** [comment]
Yes, pretty much.

In projects which use the https://github.com/solidjs/solid framework, they require a [babel preset](https://github.com/solidjs/solid/tree/main/packages/babel-preset-solid) to convert JSX into solid specific runtime calls. Solid leverages the JSX ecosystem rather than implementing their own component DSL.

For TypeScript support in these projects it's currently required to use `@babel/preset-typescript` along with `tsconfig.json` like:

```json
{
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```

With the `jsx=preserve` option in `rollup-plugin-esbuild`, I was hoping I could rip out `@babel/preset-typescript` and instead transpile TS via rollup-plugin-esbuild first for faster build times. That way I could run babel _only_ on files which might be solid components (`*.tsx`).

**Comment by egoist** [comment]
Will add it soon 👌🏻
