### ISSUE TITLE
[bug] dist/index.js missing in v1.5.0

### ISSUE THREAD

**Issue by akilli** [egoist/rollup-plugin-esbuild#27]
The **dist/index.js** file is missing in the **v1.5.0** release resulting in 

`[!] Error: Cannot find module '/path/to/node_modules/rollup-plugin-esbuild/dist/index.js'. Please verify that the package.json has a valid "main" entry`

**Comment by shmidt-i** [comment]
+1, having the same problem

**Comment by akilli** [comment]
Thanks

**Comment by shmidt-i** [comment]
Thank you!

**Comment by wobsoriano** [comment]
Getting `Error: Cannot find module 'esbuild'` in ^2.5.0 again
