### ISSUE TITLE
When using Vue 3, a compilation error occurred in <></> in tsx

### ISSUE THREAD

**Issue by RanxinStart** [egoist/rollup-plugin-esbuild#299]
### Configuration used in the plugin
```js
plugins: [
    vueJsx(),
    esbuild({ 
      jsxFactory: 'vueJsxCompat',
     }),
    vue(),
]
```

### Use in code
```tsx
const CardContainer = defineComponent({
    setup(props) {
      return () => <> text </>
    }
})
```

### Compiled results
```js
const CardContainer = defineComponent({
      setup(props2) {
        return () => /* @__PURE__ */ vueJsxCompat(React.Fragment, null, " text ");
      }
});
```

![image](https://user-images.githubusercontent.com/56920162/126896310-182c82ba-40f1-41de-8350-9f78855646f4.png)

**Comment by hyrious** [comment]
try:
```js
esbuild({ jsxFactory: 'vueJsxCompat', jsxFragment: 'Fragment' })
```
Should also add `import { Fragment } from "vue"`.

**Comment by RanxinStart** [comment]
@hyrious 
I don't quite understand what you mean, it is in the plug-in configuration first
```js
esbuild({ jsxFactory: 'vueJsxCompat', jsxFragment: 'Fragment' })
```
Then after completing the compilation, add to the compiled file
import {Fragment} from "vue"?

If that’s what I mean, I prefer to use ‘<Fragment> text </Fragment>’ in the code, which is more convenient

**Comment by hyrious** [comment]
@RanxinStart
Yes, it is in plugin config. Full example here:

a.jsx:
```jsx
import { Fragment } from "vue"
export default {
  render() {
    return <>Hello, world!</>
  }
}
```

rollup.config.js
```js
import vueJsx from 'rollup-plugin-vue-jsx-compat'
import esbuild from 'rollup-plugin-esbuild'

export default {
  input: 'a.jsx',
  external: ['vue'],
  plugins: [
    vueJsx(),
    esbuild({
      jsxFactory: 'vueJsxCompat',
      jsxFragment: 'Fragment',
    }),
  ],
}
```

<samp>rollup -c</samp>
```js
import { createVNode, isVNode, Fragment } from 'vue';

// Copy from vite/src/client/vueJsxCompat.ts

const slice = Array.prototype.slice;

function vueJsxCompat(tag, props = null, children = null) {
  if (arguments.length > 3 || isVNode(children)) {
    children = slice.call(arguments, 2);
  }
  return createVNode(tag, props, children);
}

var a = {
  render() {
    return /* @__PURE__ */ vueJsxCompat(Fragment, null, "Hello, world!");
  }
};

export default a;
```

**Comment by RanxinStart** [comment]
@hyrious 
I tried to write code like this, it didn't solve the problem I wanted to solve

If there is no `import { Fragment } from "vue" `in `a.jsx`, then the result of compilation will generate an alias for Fragment, and the final result is still Fragment is undefined.
 
The result I expect is to be able to use `<> Hello, world! </>` like React without introducing Fragment every time Fragment is used.

**Comment by hyrious** [comment]
@RanxinStart
> ……like React without introducing Fragment every time Fragment is used

You can ask [vue-jsx-compact](https://github.com/xxholly32/rollup-plugin-vue-jsx/blob/master/src/vue-jsx-compat.js) plugin to do that for you. Like change the  first line of the inject file to
```js
import { createVNode, isVNode, Fragment } from "vue";
```

@xxholly32

**Comment by xxholly32** [comment]
vue created official transform library

try 

```
const vueJsx = require("@vitejs/plugin-vue-jsx");
const esbuild = require("rollup-plugin-esbuild");

export default {
  ... 
  plugins: [vueJsx(), esbuild()],
};
```
