### ISSUE TITLE
Invalid option "jsx" due to old esbuild version.

### ISSUE THREAD

**Issue by Diabl0269** [egoist/rollup-plugin-esbuild#303]
We are working in a monorepo and using rollup with this plugin for building our modules, however we started getting this error:
`Error: Transform failed with 1 error:
error: Invalid option in transform() call: "jsx"`

I debugged both the plugin and esbuild and found out that the issue was caused due to the plugin adding a "jsx" option which isn't supported in the esbuild version noted in the plugin's pacakge.json.
I was able to solve it by manually installing the latest version of esbuild, but I think that its best to also update the version the the plugin's pacakge.json.

rollup-plugin-esbuild version: 4.5.0
esbuild in the plugin's package.json: 0.12.5
My esbuild version: 0.12.7

**Comment by sauravhiremath** [comment]
Had the same issue, had to manually update the transient dependency [`esbuild`] to `v0.12.27` to make it work. 

Also `patch-package`  doesn't work here, as it doesn't support patching the `package.json` file (Reason explained [here](https://github.com/ds300/patch-package/issues/49#issuecomment-831231339))

Still waiting for a workaround :/

**Comment by egoist** [comment]
esbuild is a peer dependency, you can just install the version you want.
