### ISSUE TITLE
Support plugins / inject

### ISSUE THREAD

**Issue by antonstjernquist** [egoist/rollup-plugin-esbuild#312]
Hey, nice plugin! :)

Would be nice if plugins was supported. It would help a lot with React 17 and automatic jsx runtime.

Thanks!

**Comment by egoist** [comment]
plugins and `inject` are not supported since they are not a part of the `transform` API: https://esbuild.github.io/api/#transform-api

**Comment by mrshmllow** [comment]
is there any way that they could be?
