### ISSUE TITLE
`experimentalBundling: true` ignores `define` object

### ISSUE THREAD

**Issue by johnrees** [egoist/rollup-plugin-esbuild#314]
I've [made a branch](https://github.com/johnrees/rollup-plugin-esbuild/tree/experimental-define-bug) to demonstrate experimentalBundling not using the define config object

First I added an [extra task to package.json](https://github.com/johnrees/rollup-plugin-esbuild/blob/experimental-define-bug/package.json#L12), which uses a different config file to the current example

```
"example:experimental": "npm run build && rollup -c example/rollup.config.experimental.js",
```

[`rollup.config.js` remains unchanged](https://github.com/johnrees/rollup-plugin-esbuild/blob/experimental-define-bug/example/rollup.config.js) (except for disabling minify)

[`rollup.config.experimental.js` looks like this](https://github.com/johnrees/rollup-plugin-esbuild/blob/experimental-define-bug/example/rollup.config.experimental.js) -

```javascript
const esbuild = require('../dist/index')

export default {
  input: 'example/index.js',
  output: {
    file: 'example/dist/index.experimental.js', // different output filename
    format: 'cjs',
  },
  plugins: [
    esbuild({
      experimentalBundling: true, // enable experimental
      minify: false,
      define: {
        'process.env.MESSAGE': `"${process.env.MESSAGE}"`,
      },
    }),
  ],
}
```

I then ran -

```
MESSAGE='hello from env'  npm run example
MESSAGE='hello from env'  npm run example:experimental
```

the [output of the regular build](https://github.com/johnrees/rollup-plugin-esbuild/blob/experimental-define-bug/example/dist/index.js) was as expected

```typescript
'use strict';

class Foo {
  render() {
    return /* @__PURE__ */ React.createElement("div", {
      className: "hehe"
    }, "hello from env");
  }
}

console.log(Foo);
```

but the [experimental build output](https://github.com/johnrees/rollup-plugin-esbuild/blob/experimental-define-bug/example/dist/index.experimental.js) had not swapped in the "hello from env" message

```typescript
'use strict';

// example/foo.tsx
var Foo = class {
  render() {
    return /* @__PURE__ */ React.createElement("div", {
      className: "hehe"
    }, process.env.MESSAGE);
  }
};
var foo_default = Foo;

// example/index.js
console.log(foo_default);
```

**Comment by sxzz** [comment]
`experimentalBundling` is removed now, but replaced with `optimizeDeps`.
