### ISSUE TITLE
legalComments option doesn't apply to libraries in node_modules

### ISSUE THREAD

**Issue by beginor** [egoist/rollup-plugin-esbuild#315]
I have set `legalComments` to `none`, it can only trim the legal comments in current project, but the legal comments of library in node_modules are still in the result bundle.

My config is something like:

```js
import alias from '@rollup/plugin-alias';
import commonjs from '@rollup/plugin-commonjs';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import scss from 'rollup-plugin-scss';
import esbuild from 'rollup-plugin-esbuild';
import vue from 'rollup-plugin-vue';

// `npm run build` -> `production` is true
// `npm run dev` -> `production` is false
const production = !process.env.ROLLUP_WATCH;

/** @type { import('rollup').RollupOptions } */
export default {
  input: [
    './src/main.ts'
  ],
  output: {
    dir: 'dist',
    chunkFileNames: production ? "chunks/[name]-[hash].js" : "chunks/[name].js",
    format: 'es',
    sourcemap: !production
  },
  watch: { clearScreen: false },
  treeshake: production,
  external: [],
  plugins: [
    vue({}),
    esbuild({ tsconfig: 'tsconfig.json', sourceMap: !production, minify: production, legalComments: 'none' }),
    scss({
      output: 'dist/main.css', sass: require('sass'), sourceMap: !production,
      outputStyle: !production ? 'expanded' : 'compressed'
    }),
    alias({}),
    nodeResolve({}),
    commonjs({})
  ],
  preserveEntrySignatures: false
}
```

Any idea?

**Comment by privatenumber** [comment]
I just added legalComments option to the minifier so it should be stripped at minification: https://github.com/privatenumber/rollup-plugin-esbuild/blob/d1146719d70bdc62b292925d82b537151e32e432/src/minify.ts#L43

Previously, it was not happening in the minifier but only in the `transformer` stage, which excluded node_modules: https://github.com/egoist/rollup-plugin-esbuild/blob/11138c8585f6f1adc1405263faefabe88d518acc/src/index.ts#L84

**Comment by egoist** [comment]
You can either configure `exclude` option to include node_modules or enable `minify` to strip away legacy comments in the final bundle, thanks to @privatenumber .
