### ISSUE TITLE
bug: minification happening in script-mode for CJS

### ISSUE THREAD

**Issue by privatenumber** [egoist/rollup-plugin-esbuild#317]
## Description
When minifying a distribution targeted at CJS, it doesn't minify top-level variables. This is happening because `format` is not passed in to transform so it assumes "script" mode:
https://github.com/egoist/rollup-plugin-esbuild/blob/883971358efc30d7cc96d2e4606754091ec103d8/src/index.ts#L194

Happy to open a PR to fix

**Comment by privatenumber** [comment]
Reproduction: https://github.com/privatenumber/issue-reproductions/tree/master/reproductions/egoist/rollup-plugin-esbuild/317

**Comment by egoist** [comment]
🙆‍♀️ PR welcome
