### ISSUE TITLE
Minify format option

### ISSUE THREAD

**Issue by steffans** [egoist/rollup-plugin-esbuild#320]
Currently the esbuild `format` option is always set using `getEsbuildFormat()` for IIFE it will result in double wrapping the already created IIFE function by rollup. Example:

```
(() => {(function(o){ ... })})();
``` 

Removing the `format` option will fix the issue. I rollup already takes care defining an output format, so its not needed to do it again in esbuild minify.

**Comment by egoist** [comment]
I guess `format` is only needed for `esm` and `cjs` then, see #318 ping @privatenumber

**Comment by steffans** [comment]
Wow that was fast, thank you 👍
