### ISSUE TITLE
`exports` changed between `4.6.0` and `4.7.0`

### ISSUE THREAD

**Issue by JounQin** [egoist/rollup-plugin-esbuild#321]
![image](https://user-images.githubusercontent.com/8336744/142567004-713a2aa4-58c3-4f9a-b5fe-9f9f0043c31a.png)

https://unpkg.com/browse/rollup-plugin-esbuild@4.7.0/dist/index.js

```js
// previous
const esbuild = require('rollup-plugin-esbuild')
import esbuild from 'rollup-plugin-esbuild' // native ESM also works

esbuild({})
```

However, the above codes will just error after upgrading to `4.7.0`, I don't know how to write correct codes with native ESM and TypeScript at the same time now. :(

Maybe it's time to publish this package as cjs/esm both.

**Comment by JounQin** [comment]
cc @privatenumber

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/142569087-4ee1fcd7-b374-4aae-87f2-1a8b95972ca4.png)

`cjs` seems still wrong

https://unpkg.com/browse/rollup-plugin-esbuild@4.7.2/dist/index.js

@egoist

**Comment by egoist** [comment]
you should just use `require('rollup-plugin-esbuild').default` if using the cjs build

**Comment by JounQin** [comment]
```js
// Annotate the CommonJS export names for ESM import in node:
0 &&
  (module.exports = {
    minify,
  })
```

Sorry, I just noticed `0 &&` what means the following `module.exports = ` will never be executed.

The generated codes are a bit strange. 🤣
