### ISSUE TITLE
Generated sourcemap maybe broken

### ISSUE THREAD

**Issue by nujarum** [egoist/rollup-plugin-esbuild#329]
I think the generated sourcemap is probably broken.

### Environment

| name                  | version           |
| --------------------- | ----------------- |
| Node.js               | 14.19.0 / 16.13.2 |
| esbuild               | 0.14.18           |
| rollup                | 2.67.0            |
| rollup-plugin-esbuild | 4.8.2             |

### Procedure for reproducing
1. Prepare a simple TypeScript file as shown below.

    <details open>
    <summary>index.ts</summary>
    
    ```ts
    export function print1() {
        console.log(1);
    }
    
    export function print2() {
        console.log(2);
    }
    
    export function print3() {
        console.log(3);
    }
    ```
    
    </details>

2. Transpile it with the rollup config file like the following.

    <details open>
    <summary>rollup.config.js</summary>
    
    ```js
    import esbuild from 'rollup-plugin-esbuild';
    
    export default [
        {
            input: './src/index.ts',
            output: {
                file: './dist/index.js',
                format: 'cjs',
                sourcemap: true,
            },
            plugins: [
                esbuild({
                    target: 'es2020',
                    // sourcemap: true,
                }),
            ],
        },
    ];
    ```
    
    </details>

3. The following `index.js.map` is generated with `index.js`, but it seems to be broken.

    ```json
    {"version":3,"file":"index.js","sources":["../src/index.ts"],"sourcesContent":["export function print1() {\n    console.log(1);\n}\n\nexport function print2() {\n    console.log(2);\n}\n\nexport function print3() {\n    console.log(3);\n}\n"],"names":[],"mappings":";;;;AAAO,SAAS,MAAM,GAAG;AACzB,EAAE,OAAO,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC;AACjB,CAAC;AACM,SAAS,MAAM,GAAG;AACzB,EAAE,OAAO,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC;AACjB,CAAC;AACM,SAAS,MAAM,GAAG;AACzB,EAAE,OAAO,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC;AACjB;;;;;;"}
    ```

    You can check if the SourceMap is correct by using a tool like ["Source Map Visualization"](http://evanw.github.io/source-map-visualization/).

-----
Note that the sourcemap is correct when building with `esbuild` alone, without `rollup` and its plugins.
I apologize if this is my misunderstanding or incorrect usage.
Best regards,

**Comment by glebcha** [comment]
Same here, checked with http://evanw.github.io/source-map-visualization/ and found that generated sourcemap is incorrect.
@egoist can you take care of this issue?

**Comment by nujarum** [comment]
As for me, I worked around this issue by creating my own plugin and using it instead.
It outputs the correct SourceMap.

I'm happy to help the author @egoist and others who are facing this issue, so I'll post the workaround here.
This workaround only supports the `*.ts` extension, but for now it is good enough for me because I only build TypeScripts.

<details open>
<summary>rollup-plugin-esbuild.mjs</summary>

```js
import { existsSync } from 'fs';
import { dirname, relative, resolve } from 'path';
import { transform } from 'esbuild';

const defaultOptions = {
    treeShaking: true,
};

export default function esbuild(options) {
    options = { ...defaultOptions, ...options };
    options.format = 'esm';
    options.loader = 'ts';
    options.sourcemap = true;
    return {
        name: 'esbuild',
        resolveId(source, importer, opts) {
            // console.log('resolveId:');
            // console.dir({ source, importer, opts }, { depth: null });
            if (!importer || source.endsWith('.ts')) {
                return source;
            }
            const dirPath = dirname(importer);
            let path;
            if (existsSync(path = resolve(dirPath, source, 'index.ts'))) {
                return path;
            } else if (existsSync(path = resolve(dirPath, source + '.ts'))) {
                return path;
            } else {
                console.error({ source, importer, options: opts });
                path = relative('.', resolve(importer, source));
                throw new Error(`ENOENT: ${path.replace(/\\/g, '/')}`);
            }
        },
        async transform(src, id) {
            options.sourcefile = id;
            const { code, map } = await transform(src, options);
            return { code, map };
        },
    };
};
```

</details>

<details open>
<summary>rollup.config.js</summary>

```js
// import esbuild from 'rollup-plugin-esbuild';
import esbuild from './rollup-plugin-esbuild.mjs';

export default [
    // Same configuration as before
];
```

</details>

-----

@glebcha 

The above workaround only supports the `*.ts` extension, but with a little implementation, it should be able to handle `*.sass` and other files.

**Comment by glebcha** [comment]
@nujarum I used another great rollup plugin which has no problems at all.
Will be great if @egoist can dig deeper and fix sourcemap issue later.
