### ISSUE TITLE
add new esbuild minifier options

### ISSUE THREAD

**Issue by jdalton** [egoist/rollup-plugin-esbuild#331]
esbuild has a new minify option:

* mangleProps

See https://github.com/evanw/esbuild/issues/218

**Comment by panoply** [comment]
Hey @jdalton, the plugin consumes the esbuild version your project is using, you can leverage the options as long as you are using an esbuild version that support it.

**Comment by jdalton** [comment]
The `rollup-plugin-esbuild` hard codes which options are passable to `esbuild`:
https://github.com/egoist/rollup-plugin-esbuild/blob/dev/src/minify.ts#L36-L47

**Comment by panoply** [comment]
Ouff. 🤦🏼‍♂️  I looked at the [spread](https://github.com/egoist/rollup-plugin-esbuild/blob/dev/src/minify.ts#L70-L72) like an absolute knob. apologies.
