### ISSUE TITLE
Extend esbuild types 

### ISSUE THREAD

**Issue by panoply** [egoist/rollup-plugin-esbuild#332]
Hey @egoist,

Thanks for your all your OS work and bringing support for esbuild to Rollup. Looking over the code the way in which types are applied could be improved. Folks tend to rely heavily on Intellisense capabilities within editors and as we see in https://github.com/egoist/rollup-plugin-esbuild/issues/331 devs will assume something it not supported when an option is not made available in completions.

We only need to omit the `CommonOptions` that this plugin does not support. Here is a refined approach you _could_ leverage that will extend the ESBuild types, opposed to the interface used in [index.ts](https://github.com/egoist/rollup-plugin-esbuild/blob/dev/src/index.ts#L28-L62)

Let me know if you need a PR and I try get around to it. 

```ts
import type { CommonOptions, Loader } from 'esbuild';

type OmitOptions = Omit<CommonOptions, (
  | 'sourcesContent'
  | 'sourcemap'
  | 'sourceRoot'
  | 'color'
  | 'logLevel'
  | 'logLimit'
)>

type MinifyOptions = Omit<OmitOptions, (
  | 'format'
  | 'sourcesContent'
  | 'globalName'
  | 'define'
  | 'pure'
  | 'jsx'
  | 'jsxFactory'
  | 'jsxFragment'
)>

export interface ESBuildOptions extends OmitOptions {
  sourceMap?: boolean;
  optimizeDeps?: MarkOptional<OptimizeDepsOptions, 'cwd' | 'sourceMap'>
  /**
   * Use this tsconfig file instead
   * Disable it by setting to `false`
   */
  tsconfig?: string | false;
  /**
   * Map extension to esbuild loader
   * Note that each entry (the extension) needs to start with a dot
   */
  loaders?: {
    [ext: string]: Loader | false;
  };
}
```

**Comment by sxzz** [comment]
Closing due to resolved.
