### ISSUE TITLE
Support rollup@v3

### ISSUE THREAD

**Issue by Mister-Hope** [egoist/rollup-plugin-esbuild#355]
https://github.com/rollup/rollup/tree/v3.0.0

```
└─┬ rollup-plugin-esbuild 4.10.1
  └── ✕ unmet peer rollup@"^1.20.0 || ^2.0.0": found 3.0.0
```

**Comment by matteosacchetto** [comment]
I know it got merged, but to the `dev` branch and not `main` so it has not been released yet.
Any chance we could have the support for rollup v3 released any time soon? 

Thank you 😃 
Matteo
