### ISSUE TITLE
No clean way to disable exclude

### ISSUE THREAD

**Issue by KenjiTakahashi** [egoist/rollup-plugin-esbuild#362]
Since the code is doing `exclude || EXCLUDE_REGEXP`, supplying `null` or `""` (which are valid values for the `FilterPattern`) still ends up with the default exclude.
The only way that works at the moment seems to be `[]`, because that happens to not be "falsy" in JS.

**Comment by sxzz** [comment]
This is because in JavaScript we have no way of knowing whether the user wants to use the default value or leave it empty. Most libraries are designed this way.
I think it's a good design to pass `[]` an empty array to emphasize avoiding exclusions.
