### ISSUE TITLE
Error in a project using decorators if esbuild version is >= 0.18.0 

### ISSUE THREAD

**Issue by Leksat** [egoist/rollup-plugin-esbuild#365]
Starting from [v0.18.0](https://github.com/evanw/esbuild/releases/tag/v0.18.0) `esbuild` throws an error if TypeScript decorators are used in the project.

```
ERROR: Experimental decorators are not currently enabled
```

This is because `esbuild` now checks for `experimentalDecorators: true` in tsconfig (https://github.com/evanw/esbuild/commit/6f2c029071d4d791adb5ac77cead34284bc446b8).

Originally it was reported as a bug to https://github.com/evanw/esbuild/issues/3163
But it looks like `rollup-plugin-esbuild` just does not pass `experimentalDecorators` option to `esbuild`.

Possible solutions:
- pass `experimentalDecorators` option to `transform` (the one we get from tsconfig? or maybe always `true`?)
- restrict `esbuild` version to `< 0.18.0`

**Comment by nielsvanvelzen** [comment]
I'm also affected by this issue. #366 seems like a good fix. It would be nice to see it merged into a release. @egoist could you take a look at #366 and possibly release a new version?

**Comment by vmizg** [comment]
This still does not work with extended tsconfig. Created a new issue for that in #371.
