### ISSUE TITLE
Plugin does not resolve "extends" field for tsconfig

### ISSUE THREAD

**Issue by vmizg** [egoist/rollup-plugin-esbuild#371]
ESBuild themselves support the "extends" field in tsconfig. This still prevents my build when using the new version due to missing TS configuration options from the base file. My base file has `"experimentalDecorators": true`, which, when not read, results in the issue reported here: https://github.com/egoist/rollup-plugin-esbuild/issues/365.

For example:

tsconfig.base.json
```json
{
  "compilerOptions": {
    "experimentalDecorators": true
  }
}
```

tsconfig.json
```json
{
  "extends": "./tsconfig.base.json"
}
```

The problem here is that the [referenced fix](https://github.com/egoist/rollup-plugin-esbuild/pull/370/files) uses the `tsconfigRaw` property which expects a fully resolved config.

Could we not use the `tsconfig` property instead of `tsconfigRaw` and leave the reading and resolution of the file contents to [esbuild, as it supports that out of the box](https://esbuild.github.io/api/#tsconfig)?

**Comment by vmizg** [comment]
I'll be using [get-tsconfig](https://github.com/privatenumber/get-tsconfig) for the time being to overcome this by manually passing `tsconfigRaw` to the options object. Hope this helps someone who stumbles upon this.

**Comment by sxzz** [comment]
Fixed!

**Comment by vmizg** [comment]
That was quick. Thanks, @sxzz!
