### ISSUE TITLE
Vite Plugin type error 

### ISSUE THREAD

**Issue by lixiaofa** [egoist/rollup-plugin-esbuild#373]
Describe the bug:
![image](https://github.com/egoist/rollup-plugin-esbuild/assets/23230215/93894716-1b68-4049-9d07-364de35892a4)

**Comment by sxzz** [comment]
We just upgraded to Rollup 4, but Vite 4 only is using Rollup 3. So there's a type error. But it won't break our plugin. Just add `@ts-ignore` or `as any`.
