### ISSUE TITLE
Could not resolve './foo' from example/index.js

### ISSUE THREAD

**Issue by ws456999** [egoist/rollup-plugin-esbuild#4]
when i move  `foo.tsx` to `foo/index.tsx`

cound't resolve module correctly

**Comment by aelbore** [comment]
@ws456999 can you try this?

foo/index.tsx
```javascript
export default class Foo {
  render() {
    return <div className="hehe">hello there!!!</div>
  }
}
```
index.js
```
import Foo from './foo/index'
console.log(Foo)
```

**Comment by ws456999** [comment]
@aelbore ，my project have too much such case
Locate modules using the [Node resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together) in webpack，how can i use same rule with some config or plugins?

**Comment by aelbore** [comment]
@ws456999 the thing is if you have foo/index.tsx and foo.tsx exist

**Comment by ws456999** [comment]
> @ws456999 the thing is if you have foo/index.tsx and foo.tsx exist

It's two question,

1.  esbuild don't resolve module like Node resolution algorithm;

2. the priority of location modules

I only care about the first question，Do you have any ideas?

**Comment by aelbore** [comment]
@aelbore 
```javascript
  const coreModule = (resolved: string) => {
    if (existsSync(resolved) && statSync(resolved).isDirectory()) {
      for (const loader of loaders) {
        const file = join(resolved, `index.${loader}`)
        if (existsSync(file)) {
          return file
        }
      }
    }
    return null
  }

  const loadFile = (resolved: string) => {
    for (const loader of loaders) {
      const file = `${resolved}.${loader}`
      if (existsSync(file)) {
        return file
      }
    }
    return null
  }

        let file = loadFile(resolved)
        if (file) return file
        if (!file) {
          file = coreModule(resolved)
          if (file) return file
        }


```

**Comment by ws456999** [comment]
@aelbore 
it works for me! thanks a lot.

**Comment by ws456999** [comment]
looking forward to your next version

**Comment by aelbore** [comment]
> looking forward to your next version
@ws456999 
#5
