### ISSUE TITLE
tsconfig.json support?

### ISSUE THREAD

**Issue by plashenkov** [egoist/rollup-plugin-esbuild#70]
Hi there!

Thanks for the helpful plugin!
I'm trying to integrate esbuild into rollup using your plugin and it seems that it doesn't support tsconfig.json completely?
At least it doesn't respect `compilerOptions.baseUrl` and `compilerOptions.paths`.
These are path aliases which allow to write
```ts
import '@alias/module'
```
instead of
```ts
import `../../../../../../../../some-folder/module`
```
(well, I think you know, but just for clarity :) )
And as far as I know esbuild itself supports these options (https://github.com/evanw/esbuild/issues/60 and https://github.com/evanw/esbuild/issues/38#issuecomment-639784830).

Or maybe I missed something?

**Comment by ycnmhd** [comment]
found a workaround using @rollup/plugin-alias
```
import path from "path";
import resolve from "rollup-plugin-node-resolve";
import esbuild from "rollup-plugin-esbuild";
import alias from "@rollup/plugin-alias";

const customResolver = resolve({
  extensions: [".tsx", ".ts"]
});
const projectRootDir = path.resolve(__dirname);
const entries = Object.entries({
  "::helpers/*": ["./src/helpers/*"],
  "::hooks/*": ["./src/hooks/*"],
    /**/
}).map(([alias, value]) => ({
  find: new RegExp(`${alias.replace("/*", "")}`),
  replacement: path.resolve(projectRootDir, `${value[0].replace("/*", "")}`)
}));
export default {
  /**/
  plugins: [
    alias({
      entries,
      customResolver
    }),
    esbuild({
      /**/
    })
  ]
};
```

**Comment by egoist** [comment]
The solution is to use `@rollup/plugin-alias` as @ycnmhd said, there's also [alias-hq](https://github.com/davestewart/alias-hq/blob/master/docs/integrations.md#rollup) (by @davestewart) to reduce boilerplate code.

**Comment by davestewart** [comment]
Thanks for the mention @egoist

**Comment by peats-bond** [comment]
> The solution is to use `@rollup/plugin-alias` as @ycnmhd said

The workaround using `@rollup/plugin-alias` adds ~5 seconds of build time to my project. @egoist do you have plans to better support `tsconfig.json`? It looks like the esbuild library supports more fields than you support right now: 
- https://esbuild.github.io/content-types/#tsconfig-json
- https://github.com/evanw/esbuild/blob/36073fc86ea3acf77764fa8fb6472e02243305ee/lib/shared/types.ts#L161
- https://github.com/evanw/esbuild/blob/36073fc86ea3acf77764fa8fb6472e02243305ee/lib/shared/types.ts#L54

**Comment by egoist** [comment]
@peats-bond path alias is not part of esbuild's `transform` api

**Comment by JensDll** [comment]
I couldn't get the newer [@rollup/plugin-node-resolve](https://github.com/rollup/plugins/tree/master/packages/node-resolve) to work as the [`customResolver`](https://github.com/rollup/plugins/tree/master/packages/alias#customresolver) argument. However, in my trivial case, a simple [`resolveId`](https://rollupjs.org/guide/en/#resolveid) function that looks through a list of extensions was enough to resolve and bundle the aliased modules:

```ts
import alias, { type ResolverFunction } from '@rollup/plugin-alias'

function resolveExtensions(extensions: string[]): ResolverFunction {
  return async function customResolver(source) {
    for (const extension of extensions) {
      try {
        const moduleInfo = await this.load({ id: source + extension })
        return moduleInfo.id
      } catch {}
    }

    return null
  }
}

alias({
  customResolver: resolveExtensions(['.ts']),
  entries: [/* ... */]
})
```

**Comment by sxzz** [comment]
See https://github.com/egoist/rollup-plugin-esbuild/issues/70#issuecomment-743196686, and let's track https://github.com/evanw/esbuild/issues/394. As this project is a wrapper of esbuild.

**Comment by castarco** [comment]
Notice that besides `tsconfig.json`'s paths, we also have `package.json`'s `imports` field.

Some people are using the later because it's more generic, but `rollup-plugin-esbuild` seems to have the same (or similar) problems with it.
