### ISSUE TITLE
sourceMap property broken

### ISSUE THREAD

**Issue by David-Else** [egoist/rollup-plugin-esbuild#76]
```
import esbuild from "rollup-plugin-esbuild";

export default {
  input: "src/mod.ts",
  plugins: [
    esbuild({
      watch: process.argv.includes("--watch"),
      minify: process.env.BUILD === "production",
      sourceMap: true,
    }),
  ],
  output: {
    dir: "dist",
    format: "esm",
  },
};
```
```
[!] (plugin esbuild) Error: Transform failed with 1 error:
error: Must use "sourcefile" with "sourcemap" to set the original file name
```
but the following seems to work, is this config correct? It is not using the extension as show in the README:

```
import esbuild from "rollup-plugin-esbuild";

export default {
  input: "src/mod.ts",
  plugins: [
    esbuild({
      watch: process.argv.includes("--watch"),
      minify: process.env.BUILD === "production",
    }),
  ],
  output: {
    dir: "dist",
    format: "esm",
    sourcemap: true,
  },
};
```
Here is my `tsconfig,json` in case it helps:
```
{
  "compilerOptions": {
    "target": "es2019",
    "module": "ESNext",
    "moduleResolution": "node",
    "sourceMap": true,
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true
  },
  "include": ["src/**/*.ts", ".eslintrc.js", "rollup.config.js"],
  "exclude": ["node_modules"]
}
```

**Comment by egoist** [comment]
I can't reproduce it with the latest version, btw the plugin option `sourceMap` defaults to `true`, to generate sourcemap file you only need to set rollup's output option `sourcemap` to `true`

**Comment by bestickley** [comment]
@egoist, so there is no difference between `sourceMap` in rollup's output property and this plugin? Why have the option in the plugin, then?

Also, when you said:
> btw the plugin option sourceMap defaults to true
Does that mean the documentation is wrong when it has `sourceMap: false, // default`?

Appreciate your insight.

**Comment by egoist** [comment]
Just updated the readme to reflect this.

**Comment by savelifeme** [comment]
将 sourceMap 设置为false，结果还是会生成map文件，是什么原因导致的呀？
