### ISSUE TITLE
Don't take `target` value from tsconfig.json

### ISSUE THREAD

**Issue by David-Else** [egoist/rollup-plugin-esbuild#77]
Please read this https://github.com/evanw/esbuild/issues/330 and Evan's reply.

As the esbuild `target` and tsc `target` are so different I don't think it makes sense to take the target from tsconfig.json in this extension.

**Comment by egoist** [comment]
I've published a fix to use lowercased value, for now, to avoid breaking change. Maybe I'll remove that in a new major release in the future.
